crm/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls import url
from rest_framework import permissions


openapi_info = openapi.Info(
    title="Crm API",
    default_version="v1",
)

schema_view = get_schema_view(
    openapi_info,
    public=True,
    url=os.getenv("SWAGGER_ROOT_URL"),
    permission_classes=(permissions.AllowAny,),
)


app_name = "crm"

urlpatterns = [
    url(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    url(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    url(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path("api/", include("common.app_urls", namespace="common_urls")),
    path("logout/", views.LogoutView, {"next_page": "/login/"}, name="logout"),
]


if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

invoices/urls.py
# from django.urls import path
# from invoices.views import *

# app_name = "invoices"


# urlpatterns = [
#     path("", invoices_list, name="invoices_list"),
#     path("create/", invoices_create, name="invoices_create"),
#     path("detail/<int:invoice_id>/", invoice_details, name="invoice_details"),
#     path("edit/<int:invoice_id>/", invoice_edit, name="invoice_edit"),
#     path("delete/<int:invoice_id>/", invoice_delete, name="invoice_delete"),
#     path("download/<int:invoice_id>/", invoice_download, name="invoice_download"),
#     path("send-mail/<int:invoice_id>/", invoice_send_mail, name="invoice_send_mail"),
#     path(
#         "cancelled-mail/<int:invoice_id>/",
#         invoice_change_status_cancelled,
#         name="invoice_change_status_cancelled",
#     ),
#     path(
#         "paid-mail/<int:invoice_id>/",
#         invoice_change_status_paid,
#         name="invoice_change_status_paid",
#     ),
#     path("comment/add/", AddCommentView.as_view(), name="add_comment"),
#     path("comment/edit/", UpdateCommentView.as_view(), name="edit_comment"),
#     path("comment/remove/", DeleteCommentView.as_view(), name="remove_comment"),
#     path("attachment/add/", AddAttachmentView.as_view(), name="add_attachment"),
#     path(
#         "attachment/remove/", DeleteAttachmentsView.as_view(), name="remove_attachment"
#     ),
#     path("get_teams_and_users/", get_teams_and_users, name="get_teams_and_users"),
# ]

cases/models.py
import arrow
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from accounts.models import Account
from contacts.models import Contact
from common.models import Org, Profile
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE
from planner.models import Event
from teams.models import Teams


class Case(models.Model):
    name = models.CharField(pgettext_lazy("Name of the case", "Name"), max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(
        choices=CASE_TYPE, max_length=255, blank=True, null=True, default=""
    )
    account = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="accounts_cases",
    )
    contacts = models.ManyToManyField(Contact)
    # closed_on = models.DateTimeField()
    closed_on = models.DateField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(Profile, related_name="case_assigned_users")
    created_by = models.ForeignKey(
        Profile, related_name="case_created_by", on_delete=models.SET_NULL, null=True
    )
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)
    teams = models.ManyToManyField(Teams, related_name="cases_teams")
    org = models.ForeignKey(
        Org, on_delete=models.SET_NULL, null=True, blank=True, related_name="case_org"
    )


    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.name

    @property
    def get_team_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        return Profile.objects.filter(id__in=team_user_ids)

    @property
    def get_team_and_assigned_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = team_user_ids + assigned_user_ids
        return Profile.objects.filter(id__in=user_ids)

    @property
    def get_assigned_users_not_in_teams(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = set(assigned_user_ids) - set(team_user_ids)
        return Profile.objects.filter(id__in=list(user_ids))

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Meeting",
            status="Planned",
        )

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting"
        ).exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Task",
            status="Planned",
        )

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task"
        ).exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Call",
            status="Planned",
        )

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call"
        ).exclude(status="Planned")

    def get_assigned_user(self):
        return Profile.objects.get(id=self.assigned_to_id)

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

invoices/models.py
import datetime
import arrow
from django.db import models
from django.utils.translation import ugettext_lazy as _
from common.models import Address, User, Org
from common.utils import CURRENCY_CODES
from accounts.models import Account
from phonenumber_field.modelfields import PhoneNumberField
from teams.models import Teams


class Invoice(models.Model):
    """Model definition for Invoice."""

    INVOICE_STATUS = (
        ("Draft", "Draft"),
        ("Sent", "Sent"),
        ("Paid", "Paid"),
        ("Pending", "Pending"),
        ("Cancelled", "Cancel"),
    )

    invoice_title = models.CharField(_("Invoice Title"), max_length=50)
    invoice_number = models.CharField(_("Invoice Number"), max_length=50)
    from_address = models.ForeignKey(
        Address,
        related_name="invoice_from_address",
        on_delete=models.SET_NULL,
        null=True,
    )
    to_address = models.ForeignKey(
        Address, related_name="invoice_to_address", on_delete=models.SET_NULL, null=True
    )
    name = models.CharField(_("Name"), max_length=100)
    email = models.EmailField(_("Email"))
    assigned_to = models.ManyToManyField(User, related_name="invoice_assigned_to")
    # quantity is the number of hours worked
    quantity = models.PositiveIntegerField(default=0)
    # rate is the rate charged
    rate = models.DecimalField(default=0, max_digits=12, decimal_places=2)
    # total amount is product of rate and quantity
    total_amount = models.DecimalField(
        blank=True, null=True, max_digits=12, decimal_places=2
    )
    tax = models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2)
    currency = models.CharField(
        max_length=3, choices=CURRENCY_CODES, blank=True, null=True
    )
    phone = PhoneNumberField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, related_name="invoice_created_by", on_delete=models.SET_NULL, null=True
    )

    amount_due = models.DecimalField(
        blank=True, null=True, max_digits=12, decimal_places=2
    )
    amount_paid = models.DecimalField(
        blank=True, null=True, max_digits=12, decimal_places=2
    )
    is_email_sent = models.BooleanField(default=False)
    status = models.CharField(choices=INVOICE_STATUS, max_length=15, default="Draft")
    details = models.TextField(_("Details"), null=True, blank=True)
    due_date = models.DateField(blank=True, null=True)
    accounts = models.ManyToManyField(Account, related_name="accounts_invoices")
    teams = models.ManyToManyField(Teams, related_name="invoices_teams")

    org = models.ForeignKey(
        Org, on_delete=models.SET_NULL, null=True, blank=True
    )
    tax = models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2)

    class Meta:
        """Meta definition for Invoice."""

        verbose_name = "Invoice"
        verbose_name_plural = "Invoices"

    def __str__(self):
        """Unicode representation of Invoice."""
        return self.invoice_number

    def save(self, *args, **kwargs):
        if not self.invoice_number:
            self.invoice_number = self.invoice_id_generator()
            while Invoice.objects.filter(invoice_number=self.invoice_number).exists():
                self.invoice_number = self.invoice_id_generator(
                    prev_invoice_number=self.invoice_number
                )
        super(Invoice, self).save(*args, **kwargs)

    def invoice_id_generator(self, prev_invoice_number=None):
        if prev_invoice_number:
            prev_invoice_number += 1
            return prev_invoice_number
        date = datetime.datetime.now().strftime("%d%m%Y")
        return int(date + "0001")

    def formatted_total_amount(self):
        return self.currency + " " + str(self.total_amount)

    def formatted_rate(self):
        return str(self.rate) + " " + self.currency

    def formatted_total_quantity(self):
        return str(self.quantity) + " " + "Hours"

    def is_draft(self):
        if self.status == "Draft":
            return True
        else:
            return False

    def is_sent(self):
        if self.status == "Sent" and self.is_email_sent == False:
            return True
        else:
            return False

    def is_resent(self):
        if self.status == "Sent" and self.is_email_sent == True:
            return True
        else:
            return False

    def is_paid_or_cancelled(self):
        if self.status in ["Paid", "Cancelled"]:
            return True
        else:
            return False

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

    @property
    def get_team_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        return User.objects.filter(id__in=team_user_ids)

    @property
    def get_team_and_assigned_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = team_user_ids + assigned_user_ids
        return User.objects.filter(id__in=user_ids)

    @property
    def get_assigned_users_not_in_teams(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = set(assigned_user_ids) - set(team_user_ids)
        return User.objects.filter(id__in=list(user_ids))


class InvoiceHistory(models.Model):
    """Model definition for InvoiceHistory.
    This model is used to track/keep a record of the updates made to original invoice object."""

    INVOICE_STATUS = (
        ("Draft", "Draft"),
        ("Sent", "Sent"),
        ("Paid", "Paid"),
        ("Pending", "Pending"),
        ("Cancelled", "Cancel"),
    )
    invoice = models.ForeignKey(
        Invoice, on_delete=models.CASCADE, related_name="invoice_history"
    )
    invoice_title = models.CharField(_("Invoice Title"), max_length=50)
    invoice_number = models.CharField(_("Invoice Number"), max_length=50)
    from_address = models.ForeignKey(
        Address,
        related_name="invoice_history_from_address",
        on_delete=models.SET_NULL,
        null=True,
    )
    to_address = models.ForeignKey(
        Address,
        related_name="invoice_history_to_address",
        on_delete=models.SET_NULL,
        null=True,
    )
    name = models.CharField(_("Name"), max_length=100)
    email = models.EmailField(_("Email"))
    assigned_to = models.ManyToManyField(
        User, related_name="invoice_history_assigned_to"
    )
    # quantity is the number of hours worked
    quantity = models.PositiveIntegerField(default=0)
    # rate is the rate charged
    rate = models.DecimalField(default=0, max_digits=12, decimal_places=2)
    # total amount is product of rate and quantity
    total_amount = models.DecimalField(
        blank=True, null=True, max_digits=12, decimal_places=2
    )
    currency = models.CharField(
        max_length=3, choices=CURRENCY_CODES, blank=True, null=True
    )
    phone = PhoneNumberField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    # created_by = models.ForeignKey(
    #     User, related_name='invoice_history_created_by',
    #     on_delete=models.SET_NULL, null=True)
    updated_by = models.ForeignKey(
        User,
        related_name="invoice_history_created_by",
        on_delete=models.SET_NULL,
        null=True,
    )

    amount_due = models.DecimalField(
        blank=True, null=True, max_digits=12, decimal_places=2
    )
    amount_paid = models.DecimalField(
        blank=True, null=True, max_digits=12, decimal_places=2
    )
    is_email_sent = models.BooleanField(default=False)
    status = models.CharField(choices=INVOICE_STATUS, max_length=15, default="Draft")
    # details or description here stores the fields changed in the original invoice object
    details = models.TextField(_("Details"), null=True, blank=True)
    due_date = models.DateField(blank=True, null=True)

    def __str__(self):
        """Unicode representation of Invoice."""
        return self.invoice_number

    class Meta:
        ordering = ("created_on",)

    def formatted_total_amount(self):
        return self.currency + " " + str(self.total_amount)

    def formatted_rate(self):
        return str(self.rate) + " " + self.currency

    def formatted_total_quantity(self):
        return str(self.quantity) + " " + "Hours"

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

invoices/templates/assigned_to_email_template.html
{% extends 'root_email_template_new.html' %}

{% block heading %}

Hello {{ user }}
{% endblock heading %}


{% block content_body %}
{{invoice_created_by}} shared an invoice with you - {{invoice_title}}
{% endblock content_body %}

{% block button_link %}
<div style="margin-bottom:20px">
    <a href="{{url}}"
        style="display:inline-block;width:170px;background:#38abdd;padding:10px;text-align:center;color:#fff;font-size:1rem;font-weight:600;margin:0px auto;margin-bottom:20px;border-radius:5px;text-decoration:none;display:block">Click Here</a>
</div>
{% endblock button_link %}

invoices/templates/invoice_cancelled.html
{% extends 'root_email_template.html' %}

{% block content_body %}
<h3>

    Invoice has been Cancelled

</h3>
{% endblock content_body %}


{% comment %}
{% block button_link %}
<div style="margin-bottom:20px">
    <a href="{{url}}"
        style="display:inline-block;width:170px;background:#38abdd;padding:10px;text-align:center;color:#fff;font-size:1rem;font-weight:600;margin:0px auto;margin-bottom:20px;border-radius:5px;text-decoration:none;display:block">Click
        Here</a>
</div>
{% endblock button_link %}
{% endcomment %}

invoices/templates/invoice_detail_email.html
{% extends 'root_email_template_new.html' %}

{% block content_body %}
<h3>

    An Invoice has been generated

</h3>
{% endblock content_body %}

{% block button_link %}
<div style="margin-bottom:20px">
    <a href="{{url}}"
        style="display:inline-block;width:170px;background:#38abdd;padding:10px;text-align:center;color:#fff;font-size:1rem;font-weight:600;margin:0px auto;margin-bottom:20px;border-radius:5px;text-decoration:none;display:block">Click
        Here</a>
</div>
{% endblock button_link %}

invoices/templates/invoices_create.html
{% extends 'sales/base.html' %}
{% load static %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'invoices:invoices_list' %}">Invoices</a></li>
    <li class="breadcrumb-item active">{% if invoice_obj %}Edit{% else %}Create{% endif %}</li>
  </ol>
</nav>
{% endblock %}
{% block content %}
<form id="formid" action='' method="POST" novalidate enctype="multipart/form-data">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-9">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-center">
            {% if invoice_obj %}EDIT{% else %}CREATE{% endif %} INVOICE
          </div>
          <div class="row marl">
            <div class="col-md-4">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1" class="required">Invoice
                    Title{% if form.invoice_title.field.required %}<span class="error_marker"
                      style="color:red">*</span>{% endif %}</label>
                  {{ form.invoice_title }}
                  <span class="error" id="id__invoice_title">{{ form.invoice_title.errors }}</span>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Invoice Number{% if form.invoice_number.field.required %}<span
                      class="error">*</span>{% endif %}</label>
                  {{ form.invoice_number }}
                  <span class="error" id="id__invoice_number">{{ form.invoice_number.errors }}</span>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1" class="required">Name{% if form.name.field.required %}<span
                      class="error_marker" style="color:red">*</span>{% endif %}</label>
                  {{ form.name }}
                  <span class="error" id="id__name">{{ form.name.errors }}</span>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1" class="required">Email{% if form.email.field.required %}<span
                      class="error_marker" style="color:red">*</span>{% endif %}</label>
                  {{ form.email }}
                  <span class="error" id="id__email">{{ form.email.errors }}</span>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1" class="required">Currency{% if form.currency.field.required %}<span
                      class="error_marker" style="color:red">*</span>{% endif %}</label>
                  {{ form.currency }}
                  <span class="error" id="id__currency">{{ form.currency.errors }}</span>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1" class="required">Phone{% if form.phone.field.required %}<span
                      class="error_marker" style="color:red">*</span>{% endif %}</label>
                  {{ form.phone }}
                  <span class="error" id="id__phone">{{ form.phone.errors }}</span>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="filter_col billing_block col-md-12" style="padding: 0px;">
                <div class="filter_col col-md-12">
                  <div class="form-group ">
                    <label for="exampleInputEmail1" class="required">Quantity{% if form.quantity.field.required %}<span
                        class="error_marker" style="color:red">*</span>{% endif %}</label>
                    {{ form.quantity }}
                    <span class="error" id="id__quantity">{{ form.quantity.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group ">
                    <label for="id_contacts" class="required">Rate{% if form.rate.field.required %}<span
                        class="error_marker" style="color:red">*</span>{% endif %}</label>
                    {{ form.rate }}
                    <span class="error" id="id__rate">{{ form.rate.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group ">
                    <label for="id_contacts" class="required">Total Amount{% if form.total_amount.field.required %}<span
                        class="error_marker" style="color:red">*</span>{% endif %}</label>
                    {{ form.total_amount }}
                    <span class="error" id="id__total_amount">{{ form.total_amount.errors }}</span>
                  </div>
                </div>
                <div class="filter_col billing_block col-md-12" style="padding: 0px;">
                  <div class="filter_col col-md-12">
                    <div class="form-group ">
                      <label for="id_contacts" class="required">Status{% if form.status.field.required %}<span
                          class="error_marker" style="color:red">*</span>{% endif %}</label>
                      {{ form.status }}
                      <span class="error" id="id__status">{{ form.status.errors }}</span>
                    </div>
                  </div>
                  <div class="filter_col col-md-12">
                    <div class="form-group ">
                      <label for="exampleInputEmail1">Assign To</label>
                      {{form.assigned_to}}
                      <span class="error" id="id__assigned_to">{{ form.assigned_to.errors }}</span>
                    </div>
                  </div>
                  <div class="filter_col col-md-12">
                    <div class="form-group ">
                      <label for="exampleInputEmail1">Due Date {% if form.due_date.field.required %}<span
                          class="error_marker" style="color:red">*</span>{% endif %}</label>
                      <div id="datepicker1" class='input-group date'>
                        {{ form.due_date }}
                        <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                      </div>
                      <span class="error" id="id__due_date">{{ form.due_date.errors }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="filter_col col-md-12">
                <div class="form-group ">
                  <label for="exampleInputEmail1">Details</label>
                  {{form.details}}
                  <span class="error" id="id__details">{{ form.details.errors }}</span>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">From Address</label>
                  {{ from_address_form.address_line }}
                  <span class="error" id="id__address_line">{{ from_address_form.address_line.errors }}</span>
                </div>
                {{ from_address_form.street }}
                <span class="error" id="id__street">{{ from_address_form.street.errors }}</span>
                <div class="row" style="margin-top: 10px;">
                  <div class="col-md-4">
                    {{ from_address_form.city }}
                    {{ from_address_form.city.errors }}
                    <span class="error" id="id__city">{{ to_address_form.city.errors }}</span>
                  </div>
                  <div class="col-md-4">
                    {{ from_address_form.state }}
                    <span class="error" id="id__state">{{ from_address_form.state.errors }}</span>
                  </div>
                  <div class="col-md-4">
                    {{ from_address_form.postcode }}
                    <span class="error" id="id__postcode">{{ from_address_form.postcode.errors }}</span>
                  </div>
                  <div class="col-md-12" style="margin-top: 10px;">
                    {{ from_address_form.country }}
                    <span class="error" id="id__country">{{ from_address_form.country.errors }}</span>
                  </div>
                </div>
                <br>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">To Address</label>
                  {{ to_address_form.address_line }}
                  <span class="error" id="id__address_line_">{{ to_address_form.address_line.errors }}</span>
                </div>
                {{ to_address_form.street }}
                <span class="error" id="id__street_">{{ to_address_form.street.errors }}</span>
                <div class="row" style="margin-top: 10px;">
                  <div class="col-md-4">
                    {{ to_address_form.city }}
                    {{ to_address_form.city.errors }}
                    <span class="error" id="id__city_">{{ to_address_form.city.errors }}</span>
                  </div>
                  <div class="col-md-4">
                    {{ to_address_form.state }}
                    <span class="error" id="id__state_">{{ to_address_form.state.errors }}</span>
                  </div>
                  <div class="col-md-4">
                    {{ to_address_form.postcode }}
                    <span class="error" id="id__postcode_">{{ to_address_form.postcode.errors }}</span>
                  </div>
                  <div class="col-md-12" style="margin-top: 10px;">
                    {{ to_address_form.country }}
                    <span class="error" id="id__country_">{{ to_address_form.country.errors }}</span>
                  </div>
                </div>
                <br>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-12">
              <div class="row marl buttons_row form_btn_row text-center">
                <button class="btn btn-default save" type="submit">Save</button>
                <a href="{% url 'invoices:invoices_list' %}" class="btn btn-default clear"
                  id="create_user_cancel">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>
  
</form>
{% endblock %}
{% block js_block %}
<script type="text/javascript">

  // $(document).ready(function() {
  //   $('.assigned_users').select2();
  // });
  $(document).ready(function () {
    $("#id_contacts").select2();
    $("#id_assigned_to").select2();
    $('#id_currency').select2();
    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    $('#id_due_date').datetimepicker({
      'format': 'YYYY-MM-DD',
      minDate: today
    })


    $('#id_quantity').keyup(calculate);
    $('#id_rate').keyup(calculate);
    function calculate(e) {
      $('#id_total_amount').val($('#id_quantity').val() * $('#id_rate').val());
    }

  });

  $('form#formid').ajaxForm({
    type: 'POST',
    dataType: 'json',
    url: ".",
    data: $('#formid').serialize(),
    success: function (data) {
      if (data.error) {
        $('.error').html('')
        for (var key in data.errors) {
          $('#id__' + key).html("<p>" + data.errors[key][0] + "</p>");
        };
        for (var key in data.from_address_errors) {
          $('#id__' + key).html("<p>" + data.from_address_errors[key][0] + "</p>");
        };
        for (var key in data.to_address_errors) {
          $('#id__' + key + '_').html("<p>" + data.to_address_errors[key][0] + "</p>");
          console.log($('#id__' + key + '_'))
        };
        $('#submit_btn').removeAttr('disabled')
      }
      else {
        window.location = data.success_url;
      }
    }
  });
</script>
{% endblock js_block %}